[project]
name = "bud"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "sam", email = "oyerindesamuel207@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.0.0",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.141.1",
    "groq>=1.7.0",
    "huggingface-hub>=1.30.0",
    "langchain-text-splitters>=1.1.2",
    "pymupdf4llm>=1.28.2",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "streamlit>=1.64.0",
    "streamlit-pdf>=2.0.1",
    "tiktoken>=0.14.0",
]

[project.scripts]
bud = "bud:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
